#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : ov5640_hdmi.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Mar 31 17:30:16 +0800 2026
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: ov5640_hdmi.sh [-help]
# usage: ov5640_hdmi.sh [-lib_map_path]
# usage: ov5640_hdmi.sh [-noclean_files]
# usage: ov5640_hdmi.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'ov5640_hdmi.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib v_vid_in_axi4s_v4_0_9 axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 lib_cdc_v1_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_24 axi_vdma_v6_3_10 axi_lite_ipif_v3_0_4 v_tc_v6_2_1 v_tc_v6_1_13 v_axi4s_vid_out_v4_0_11 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 proc_sys_reset_v5_0_13 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "ov5640_hdmi.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/work/vivado_2020_2/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/ipshared/4477/ov5640_capture_data_1.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_ov5640_capture_data_0_0/sim/ov5640_hdmi_ov5640_capture_data_0_0.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ipshared/6a69/SCCB_protocol.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ipshared/6a69/ov5640_reg.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ipshared/6a69/ov5640_cfg_top.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_ov5640_cfg_top_0_0/sim/ov5640_hdmi_ov5640_cfg_top_0_0.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_clk_wiz_0_0/ov5640_hdmi_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_clk_wiz_0_0/ov5640_hdmi_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_v_vid_in_axi4s_0_0/sim/ov5640_hdmi_v_vid_in_axi4s_0_0.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ipshared/16ad/asyn_rst_syn.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ipshared/16ad/dvi_encoder.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ipshared/16ad/serializer_10_to_1.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ipshared/16ad/dvi_transmitter_top.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_dvi_transmitter_top_0_3/sim/ov5640_hdmi_dvi_transmitter_top_0_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_processing_system7_0_0/sim/ov5640_hdmi_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_10 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/sim/ov5640_hdmi_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/sim/ov5640_hdmi_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_v_axi4s_vid_out_0_0/sim/ov5640_hdmi_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_xbar_0/sim/ov5640_hdmi_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_rst_ps7_0_50M_1/sim/ov5640_hdmi_rst_ps7_0_50M_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_xbar_1/sim/ov5640_hdmi_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_rst_ps7_0_50M_2/sim/ov5640_hdmi_rst_ps7_0_50M_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/sim/ov5640_hdmi.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_auto_pc_0/sim/ov5640_hdmi_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/d0f7" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ipshared/7860/hdl" +incdir+"D:/work/vivado_2020_2/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_auto_cc_0/sim/ov5640_hdmi_auto_cc_0.v" \
    "$ref_dir/../../../bd/ov5640_hdmi/ip/ov5640_hdmi_auto_pc_1/sim/ov5640_hdmi_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.ov5640_hdmi xil_defaultlib.glbl -o ov5640_hdmi_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./ov5640_hdmi_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./ov5640_hdmi.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key ov5640_hdmi_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc ov5640_hdmi_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./ov5640_hdmi.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: ov5640_hdmi.sh [-help]\n\
Usage: ov5640_hdmi.sh [-lib_map_path]\n\
Usage: ov5640_hdmi.sh [-reset_run]\n\
Usage: ov5640_hdmi.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
