# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA_Project/2020_2/CNN/proj/ov5640_hdmi_v1/ov5640_hdmi_v1.srcs/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/ov5640_hdmi_v_tc_0_0.xci
# IP: The module: 'ov5640_hdmi_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_Project/2020_2/CNN/proj/ov5640_hdmi_v1/ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/ov5640_hdmi_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Project/2020_2/CNN/proj/ov5640_hdmi_v1/ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/ov5640_hdmi_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/FPGA_Project/2020_2/CNN/proj/ov5640_hdmi_v1/ov5640_hdmi_v1.srcs/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/ov5640_hdmi_v_tc_0_0.xci
# IP: The module: 'ov5640_hdmi_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_Project/2020_2/CNN/proj/ov5640_hdmi_v1/ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/ov5640_hdmi_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA_Project/2020_2/CNN/proj/ov5640_hdmi_v1/ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/ov5640_hdmi_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov5640_hdmi_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
