set_property PACKAGE_PIN K17 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property PACKAGE_PIN H16 [get_ports TMDS_clk_p_0]
set_property PACKAGE_PIN D19 [get_ports {TMDS_data_p_0[2]}]
set_property PACKAGE_PIN C20 [get_ports {TMDS_data_p_0[1]}]
set_property PACKAGE_PIN H18 [get_ports hdmi_en_0]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_en_0]
set_property PACKAGE_PIN B19 [get_ports {TMDS_data_p_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports sccb_clk_0]
set_property PACKAGE_PIN V16 [get_ports sccb_clk_0]
set_property PACKAGE_PIN U15 [get_ports sys_rst_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n_0]
set_property PACKAGE_PIN W16 [get_ports {cam_data_0[6]}]
set_property PACKAGE_PIN P18 [get_ports {cam_data_0[0]}]
set_property PACKAGE_PIN U20 [get_ports {cam_data_0[1]}]
set_property PACKAGE_PIN P19 [get_ports {cam_data_0[2]}]
set_property PACKAGE_PIN V20 [get_ports {cam_data_0[3]}]
set_property PACKAGE_PIN R18 [get_ports {cam_data_0[4]}]
set_property PACKAGE_PIN W20 [get_ports {cam_data_0[5]}]
set_property PACKAGE_PIN R17 [get_ports {cam_data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data_0[0]}]
set_property PACKAGE_PIN T16 [get_ports cam_xclk_0]
set_property PACKAGE_PIN T17 [get_ports cam_pclk_0]
set_property PACKAGE_PIN R16 [get_ports cam_href_0]
set_property PACKAGE_PIN U18 [get_ports cam_vsync_0]
set_property PACKAGE_PIN P16 [get_ports sccb_data_0]
set_property IOSTANDARD LVCMOS33 [get_ports cam_href_0]
set_property IOSTANDARD LVCMOS33 [get_ports cam_pclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports cam_vsync_0]
set_property IOSTANDARD LVCMOS33 [get_ports cam_xclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_data_0]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam_pclk_0_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports sccb_cfg_done_0]
set_property PACKAGE_PIN T12 [get_ports sccb_cfg_done_0]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/pclk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/cam_captrue_data_0/inst/cam_data[0]} {design_1_i/cam_captrue_data_0/inst/cam_data[1]} {design_1_i/cam_captrue_data_0/inst/cam_data[2]} {design_1_i/cam_captrue_data_0/inst/cam_data[3]} {design_1_i/cam_captrue_data_0/inst/cam_data[4]} {design_1_i/cam_captrue_data_0/inst/cam_data[5]} {design_1_i/cam_captrue_data_0/inst/cam_data[6]} {design_1_i/cam_captrue_data_0/inst/cam_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/cam_captrue_data_0/inst/vid_data[0]} {design_1_i/cam_captrue_data_0/inst/vid_data[1]} {design_1_i/cam_captrue_data_0/inst/vid_data[2]} {design_1_i/cam_captrue_data_0/inst/vid_data[3]} {design_1_i/cam_captrue_data_0/inst/vid_data[4]} {design_1_i/cam_captrue_data_0/inst/vid_data[5]} {design_1_i/cam_captrue_data_0/inst/vid_data[6]} {design_1_i/cam_captrue_data_0/inst/vid_data[7]} {design_1_i/cam_captrue_data_0/inst/vid_data[8]} {design_1_i/cam_captrue_data_0/inst/vid_data[9]} {design_1_i/cam_captrue_data_0/inst/vid_data[10]} {design_1_i/cam_captrue_data_0/inst/vid_data[11]} {design_1_i/cam_captrue_data_0/inst/vid_data[12]} {design_1_i/cam_captrue_data_0/inst/vid_data[13]} {design_1_i/cam_captrue_data_0/inst/vid_data[14]} {design_1_i/cam_captrue_data_0/inst/vid_data[15]} {design_1_i/cam_captrue_data_0/inst/vid_data[16]} {design_1_i/cam_captrue_data_0/inst/vid_data[17]} {design_1_i/cam_captrue_data_0/inst/vid_data[18]} {design_1_i/cam_captrue_data_0/inst/vid_data[19]} {design_1_i/cam_captrue_data_0/inst/vid_data[20]} {design_1_i/cam_captrue_data_0/inst/vid_data[21]} {design_1_i/cam_captrue_data_0/inst/vid_data[22]} {design_1_i/cam_captrue_data_0/inst/vid_data[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/cam_captrue_data_0/inst/cam_href]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/cam_captrue_data_0/inst/cam_vsync]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/cam_captrue_data_0/inst/cam_xclk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/cam_captrue_data_0/inst/vid_active_video]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/cam_captrue_data_0/inst/vid_ce]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/cam_captrue_data_0/inst/vid_vsync]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_pclk]
