# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_ov5640_hdmi.xdc

# Block Designs: bd/ov5640_hdmi/ov5640_hdmi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi || ORIG_REF_NAME==ov5640_hdmi} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_ov5640_capture_data_0_0/ov5640_hdmi_ov5640_capture_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_ov5640_capture_data_0_0 || ORIG_REF_NAME==ov5640_hdmi_ov5640_capture_data_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_clk_wiz_0_0/ov5640_hdmi_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_clk_wiz_0_0 || ORIG_REF_NAME==ov5640_hdmi_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_v_vid_in_axi4s_0_0/ov5640_hdmi_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==ov5640_hdmi_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_dvi_transmitter_top_0_3/ov5640_hdmi_dvi_transmitter_top_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_dvi_transmitter_top_0_3 || ORIG_REF_NAME==ov5640_hdmi_dvi_transmitter_top_0_3} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_processing_system7_0_0/ov5640_hdmi_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_processing_system7_0_0 || ORIG_REF_NAME==ov5640_hdmi_processing_system7_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_axi_vdma_0_0/ov5640_hdmi_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_axi_vdma_0_0 || ORIG_REF_NAME==ov5640_hdmi_axi_vdma_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_v_tc_0_0/ov5640_hdmi_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_v_tc_0_0 || ORIG_REF_NAME==ov5640_hdmi_v_tc_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_v_axi4s_vid_out_0_0/ov5640_hdmi_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ov5640_hdmi_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_xbar_0/ov5640_hdmi_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_xbar_0 || ORIG_REF_NAME==ov5640_hdmi_xbar_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_auto_pc_0/ov5640_hdmi_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_auto_pc_0 || ORIG_REF_NAME==ov5640_hdmi_auto_pc_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_ps7_0_axi_periph_1/ov5640_hdmi_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_ps7_0_axi_periph_1 || ORIG_REF_NAME==ov5640_hdmi_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_rst_ps7_0_50M_1/ov5640_hdmi_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_rst_ps7_0_50M_1 || ORIG_REF_NAME==ov5640_hdmi_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_xbar_1/ov5640_hdmi_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_xbar_1 || ORIG_REF_NAME==ov5640_hdmi_xbar_1} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_auto_cc_0/ov5640_hdmi_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_auto_cc_0 || ORIG_REF_NAME==ov5640_hdmi_auto_cc_0} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_auto_pc_1/ov5640_hdmi_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_auto_pc_1 || ORIG_REF_NAME==ov5640_hdmi_auto_pc_1} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_axi_mem_intercon_1/ov5640_hdmi_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_axi_mem_intercon_1 || ORIG_REF_NAME==ov5640_hdmi_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_rst_ps7_0_50M_2/ov5640_hdmi_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_rst_ps7_0_50M_2 || ORIG_REF_NAME==ov5640_hdmi_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/ov5640_hdmi/ip/ov5640_hdmi_ov5640_cfg_top_0_0/ov5640_hdmi_ov5640_cfg_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov5640_hdmi_ov5640_cfg_top_0_0 || ORIG_REF_NAME==ov5640_hdmi_ov5640_cfg_top_0_0} -quiet] -quiet

# XDC: e:/FPGA_Project/2020_2/CNN/proj/ov5640_hdmi_v1/ov5640_hdmi_v1.gen/sources_1/bd/ov5640_hdmi/ov5640_hdmi_ooc.xdc
